services:
  database:
    # environment:
    #   MYSQL_PASSWORD: ${DB_PROD_PASSWORD}

  api:
    image: ghcr.io/mateja-velickovic/stockhub-backend:${BACKEND_VERSION}
    build : null
    # environment:
    #   DB_PASSWORD: ${DB_PROD_PASSWORD}

  web:
    image: ghcr.io/mateja-velickovic/stockhub-frontend:${FRONTEND_VERSION}
    build : null