services:
  database:
    command: --port=3307
    expose:
      - "3307"

  api:
    image: ghcr.io/mateja-velickovic/stockhub-backend-staging:${BACKEND_VERSION}
    build : null
    environment:
      DB_PORT: 3307
      PORT: 3001
    expose:
      - "3001"
      
  web:
    image: ghcr.io/mateja-velickovic/stockhub-frontend:${FRONTEND_VERSION}
    build : null
    environment:
      VITE_API_PROXY_TARGET: http://api:3001