services:
  api:
    image: ghcr.io/mateja-velickovic/stockhub-backend:${BACKEND_VERSION}
    build : null

  web:
    image: ghcr.io/mateja-velickovic/stockhub-frontend:${FRONTEND_VERSION}
    build : null

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./deploy/staging/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
    networks:
      - frontend_network

volumes:
  caddy_data:
  caddy_config: