services:
  api:
    image: ghcr.io/mateja-velickovic/stockhub-backend:${BACKEND_VERSION}

  web:
    image: ghcr.io/mateja-velickovic/stockhub-frontend:${FRONTEND_VERSION}
    
  caddy:
    ports:
      - "443:443"
    volumes:
      - ./deploy/prod/Caddyfile:/etc/caddy/Caddyfile